#!/bin/bash

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run -ti -u $(id -u) -v $DIRNAME:/home/build/repo -w /home/build/repo docker-build-meta-intel-media-stack bash -c "source poky/oe-init-build-env && bitbake $*"
